### ISSUE TITLE
save_error_test', ['MsSql error terminal data insert

### ISSUE THREAD

**Issue by medouzi** [Kein1945/GPS_Teltonika_Server#1]
Hello
please i need your help,
when i excute the 2nd Script DB_Damone, i always have this error : 
('save_error_test', ['MsSql error terminal data insert: TerminalDataInsert @IMEI=357454072497223, @date=1560465723, @lon=422.7642145, @lat=34.0377804, @GpsSpeed=0, @GpsCourse=0',

**Comment by Kein1945** [comment]
Looks like problem with your database. Have you tried to insert this data manually?

**Comment by medouzi** [comment]
As first, thank you for responding to my issue.
i don't know how insert this data manually, i just tried to creat table in the database GPS as mentioned in the file of configuration gps.conf.dist, but i don't now exactly its correct name table you  used in the code.
I would be grateful if you help me to insert data in database. so please can you show me the step to create table and insert data.

**Comment by Kein1945** [comment]
@medouzi Sorry, somehow I've missed you question. If it's stil relevant, fell free to open new issues. Will close that one.
